TYPE=VIEW
query=select `papeleria`.`usuario`.`id` AS `id`,`papeleria`.`usuario`.`nombre` AS `nombre`,`papeleria`.`usuario`.`clave` AS `clave` from `papeleria`.`usuario`
md5=e6341e4cb839015cda31197be7b9c67e
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001753757703498600
create-version=2
source=SELECT * FROM `usuario`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `papeleria`.`usuario`.`id` AS `id`,`papeleria`.`usuario`.`nombre` AS `nombre`,`papeleria`.`usuario`.`clave` AS `clave` from `papeleria`.`usuario`
mariadb-version=100432
